// Generated by https://quicktype.io

export interface NewsTopHeadline {
    status:       string;
    totalResults: number;
    articles:     Article[];
}

export interface Article {
    source:      Source;
    author?:      string;
    title:       string;
    description?: string;
    url:         string;
    urlToImage?:  string;
    publishedAt: string;
    content?:     string;
}

export interface Source {
    id?:   string;
    name: string;
}

export interface ArticlesByCategoryAndPage {
    [key: string]:{ //se crea de la siguiente manera para que pueda ser incrementable la llave del objeto
        page: number,
        articles: Article[]
    }
}
